# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3GG6wKTxO08GdaQuCFKWjSBAAp4qIpA

# Import statments
"""

import json

"""# Import data"""

data_path = '/content/data/'
with open(f'{data_path}train.json', 'r') as f:
    train_data = json.load(f)

with open(f'{data_path}dev.json', 'r') as f:
    dev_data = json.load(f)

"""# Dataset Inspection"""

numeric_homonyms = []

for entry_id, entry_data in train_data.items():
    homonym = entry_data.get('homonym')
    if isinstance(homonym, (int, float)): # Check for actual numeric types
        numeric_homonyms.append(homonym)
    elif isinstance(homonym, str) and homonym.isnumeric(): # Check if string can be numeric
        numeric_homonyms.append(homonym)

for entry_id, entry_data in dev_data.items():
    homonym = entry_data.get('homonym')
    if isinstance(homonym, (int, float)): # Check for actual numeric types
        numeric_homonyms.append(homonym)
    elif isinstance(homonym, str) and homonym.isnumeric(): # Check if string can be numeric
        numeric_homonyms.append(homonym)

if numeric_homonyms:
    print(f"Found numeric entries in 'homonym' column: {list(set(numeric_homonyms))}")
else:
    print("No numeric entries found in 'homonym' column.")

# Collect 'choices' lists and convert to tuples for uniqueness check
all_choicess = []
for entry_id, entry_data in train_data.items():
    if 'choices' in entry_data and isinstance(entry_data['choices'], list):
        all_choicess.append(tuple(entry_data['choices']))
for entry_id, entry_data in dev_data.items():
    if 'choices' in entry_data and isinstance(entry_data['choices'], list):
        all_choicess.append(tuple(entry_data['choices']))
unique_choicess = set(all_choicess)
print(f"Number of unique 'choices' combinations: {len(unique_choicess)}")
print(f"Example unique 'choices' combinations (first 5): {list(unique_choicess)[:5]}\n")

# Collect 'nonsensical' lists and convert to tuples for uniqueness check
all_nonsensical = []
for entry_id, entry_data in train_data.items():
    if 'nonsensical' in entry_data and isinstance(entry_data['nonsensical'], list):
        all_nonsensical.append(tuple(entry_data['nonsensical']))
for entry_id, entry_data in dev_data.items():
    if 'nonsensical' in entry_data and isinstance(entry_data['nonsensical'], list):
        all_nonsensical.append(tuple(entry_data['nonsensical']))
unique_nonsensical = set(all_nonsensical)
print(f"Number of unique 'nonsensical' combinations: {len(unique_nonsensical)}")
print(f"Example unique 'nonsensical' combinations (first 5): {list(unique_nonsensical)[:5]}")

numbers_outside_range = set()

# Check train_data
for entry_id, entry_data in train_data.items():
    if 'choices' in entry_data and isinstance(entry_data['choices'], list):
        for num in entry_data['choices']:
            if not (1 <= num <= 5):
                numbers_outside_range.add(num)

# Check dev_data
for entry_id, entry_data in dev_data.items():
    if 'choices' in entry_data and isinstance(entry_data['choices'], list):
        for num in entry_data['choices']:
            if not (1 <= num <= 5):
                numbers_outside_range.add(num)

if numbers_outside_range:
    print(f"Found numbers outside the 1-5 range in 'choices': {sorted(list(numbers_outside_range))}")
else:
    print("All numbers in 'choices' combinations are within the 1-5 range.")

columns_to_check_for_non_numeric = ['average', 'stdev']
non_numeric_entries_found = {col: [] for col in columns_to_check_for_non_numeric}

# Helper function to check if a value is numeric
def is_numeric(value):
    if isinstance(value, (int, float)):
        return True
    if isinstance(value, str):
        try:
            float(value) # Try converting to float
            return True
        except ValueError:
            return False
    return False

# Check train_data
for entry_id, entry_data in train_data.items():
    for col in columns_to_check_for_non_numeric:
        value = entry_data.get(col)
        if not is_numeric(value):
            non_numeric_entries_found[col].append(value)

# Check dev_data
for entry_id, entry_data in dev_data.items():
    for col in columns_to_check_for_non_numeric:
        value = entry_data.get(col)
        if not is_numeric(value):
            non_numeric_entries_found[col].append(value)

print("\nNon-numeric entries check results for 'average' and 'stdev':")
for col, entries in non_numeric_entries_found.items():
    if entries:
        # Display unique non-numeric entries
        print(f"  Found non-numeric entries in '{col}': {list(set(entries))}")
    else:
        print(f"  No non-numeric entries found in '{col}'.")

columns_to_check = ['judged_meaning', 'precontext', 'sentence', 'ending']
numeric_entries_found = {col: [] for col in columns_to_check}

# Check train_data
for entry_id, entry_data in train_data.items():
    for col in columns_to_check:
        value = entry_data.get(col)
        if isinstance(value, (int, float)): # Check for actual numeric types
            numeric_entries_found[col].append(value)
        elif isinstance(value, str) and value.isnumeric(): # Check if string can be numeric
            numeric_entries_found[col].append(value)

# Check dev_data
for entry_id, entry_data in dev_data.items():
    for col in columns_to_check:
        value = entry_data.get(col)
        if isinstance(value, (int, float)): # Check for actual numeric types
            numeric_entries_found[col].append(value)
        elif isinstance(value, str) and value.isnumeric(): # Check if string can be numeric
            numeric_entries_found[col].append(value)

print("\nNumeric entries check results:")
for col, entries in numeric_entries_found.items():
    if entries:
        print(f"  Found numeric entries in '{col}': {list(set(entries))}")
    else:
        print(f"  No numeric entries found in '{col}'.")

# Convert dict-of-dicts → list of entries
samples = list(data.values())

def get_story_key(sample):
    return (
        sample["homonym"],
        sample["precontext"],
        sample["sentence"],
        sample.get("ending", None)
    )

story_groups = defaultdict(list)

for s in samples:
    key = get_story_key(s)
    story_groups[key].append(s)

for story_key, items in story_groups.items():
    num = len(items)
    print("\nStory key:", story_key)
    print("Number of sense-samples:", num)
    for it in items:
        print("   - judged_meaning:", it["judged_meaning"])

sense_pairs = {}

for story_key, items in story_groups.items():
    senses = list({s["judged_meaning"] for s in items})

    sense_pairs[story_key] = senses

print("Number of story setups:", len(sense_pairs))

for story_key, senses in sense_pairs.items():
    print("\n==============================")
    print("Story:", story_key)
    print("Found senses:")
    for s in senses:
        print("  •", s)